# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [2]:
# Please consult the lectures
print("Major Difference between Vector and Matrix is "
      "Vector is 1 dimensional data and Matrix can be 2,3 or many dimensions of data. "
      "Matrix comprises of multiple vectors")

Major Difference between Vector and Matrix is Vector is 1 dimensional data and Matrix can be 2,3 or many dimensions of data. Matrix comprises of multiple vectors


**2. How to import `NumPy` library?** 

In [2]:
# To avoid overwriting the output, please code here 
import numpy as np


**3. Convert the given Python list into NumPy array and check its data type**

In [22]:
list_1 = [1,2,3,4,5]


In [153]:
# To avoid overwriting the output, please code here 
np_arr1 = np.array(list_1)
print(np_arr1)
print(type(np_arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


(array([1, 2, 3, 4, 5]), numpy.ndarray)

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [154]:
# To avoid overwriting the output, please code here
generate_array = np.arange(0,6,1)
print(generate_array)

[0 1 2 3 4 5]


array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [155]:
# To avoid overwriting the output, please code here 
empty_five = np.zeros((5))
print(empty_five)

[0. 0. 0. 0. 0.]


array([ 0.,  0.,  0.,  0.,  0.])

**6. Generate the following `matrix`.**

In [156]:
# To avoid overwriting the output, please code here 
empty_3_5 = np.zeros((3,5))
print(empty_3_5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [28]:
# To avoid overwriting the output, please code here 
ones_five = np.ones((5))
print(ones_five)

[1. 1. 1. 1. 1.]


[ 1.  1.  1.  1.  1.]


**8. Generate an array of "5" tens.**

In [158]:
# To avoid overwriting the output, please code here
tens_five = np.full(5,10,dtype=float)
print(tens_five)

[10. 10. 10. 10. 10.]


array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [159]:
# To avoid overwriting the output, please code here 
generate_array = np.arange(50,100,2)[1:]
print(generate_array)

[52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [160]:
# To avoid overwriting the output, please code here 
lin_array, step_size = np.linspace(0,1,10,retstep=True)
print(lin_array,',',step_size)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ] , 0.1111111111111111


(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [161]:
# To avoid overwriting the output, please code here 
vector_array = np.arange(0,25)
print(vector_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [22]:
# Generating vector array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [79]:
# To avoid overwriting the output, please code here 
res_matrix = np.reshape(vector_array,(5,5))
print(res_matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [24]:
# reshape to convert into 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [164]:
# To avoid overwriting the output, please code here 
print('yes we can use shape as well: ')
vector_array.shape = (5,5)
print(vector_array) 


yes we can use shape as well: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
# Using shape


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [83]:
# To avoid overwriting the output, please code here
gen_point_vector = np.arange(0.1,2.6,step=0.1)
gen_point_matrix = np.reshape(gen_point_vector,(5,5))

print(gen_point_matrix) 

[[0.1 0.2 0.3 0.4 0.5]
 [0.6 0.7 0.8 0.9 1. ]
 [1.1 1.2 1.3 1.4 1.5]
 [1.6 1.7 1.8 1.9 2. ]
 [2.1 2.2 2.3 2.4 2.5]]


array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [165]:
# To avoid overwriting the output, please code here
lin_array = np.linspace(0,24,25,dtype=int).reshape(5,5)
print(lin_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**14. What is the main difference between `linspace()` and `arange()`?**

In [166]:
# Please consult the lectures. 
# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.
print(
"""
both takes start and stop number as first and second arg.
arange uses the 3rd argument as steps between the output numbers
whereas linspace uses the 3rd argument for how many digits will be shown.
""")


both takes start and stop number as first and second arg.
arange uses the 3rd argument as steps between the output numbers
whereas linspace uses the 3rd argument for how many digits will be shown.



**15. How to generate a single random integer number using NumPy built-in function?**

In [168]:
# To avoid overwriting the output, please code here 
randint_num = np.random.randint(0,10)
print(randint_num)

6


**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [147]:
# To avoid overwriting the output, please code here 
rand_numbers = np.random.rand(7,5)
print(rand_numbers)

[[0.31856785 0.75993904 0.71816065 0.63863488 0.6740568 ]
 [0.39022631 0.87257515 0.4519559  0.72496786 0.64293097]
 [0.84088168 0.63949737 0.18415784 0.55211215 0.32299443]
 [0.04157153 0.30018616 0.35674458 0.54282673 0.48877389]
 [0.05556417 0.7748429  0.35342623 0.06228081 0.23411972]
 [0.66367832 0.65339097 0.24611438 0.57102608 0.96109501]
 [0.22272308 0.61833296 0.28580071 0.37633021 0.78836614]]


[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [169]:
# To avoid overwriting the output, please code here 
identity_matrix = np.identity(5,dtype=float) * 5
print(identity_matrix)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 